version: '3'
services:
    ezmaster-libpostal:
        container_name: ezmaster-libpostal
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/ezmaster-libpostal:1.1.1
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
